[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://netlify-rum.netlify.app 'unsafe-inline' 'unsafe-eval';"
